# Stage 1: builder
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /worker ./cmd/worker

# Stage 2: runner
FROM alpine:latest
RUN apk --no-cache add ca-certificates ffmpeg
WORKDIR /app
COPY --from=builder /worker .
COPY --from=builder /app/internal/infrastructure/persistence/postgres/migrations ./internal/infrastructure/persistence/postgres/migrations
CMD ["./worker"]